project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      
      - href: about.qmd
        text: About
      
      - href: projects.qmd
        text: Projects
        
      - href: images.qmd
        text: Photography
        
      - text: Games
        href: https://alnez.itch.io/
      
      - icon: github
        text: Github
        href: https://github.com/Alnez1953
      
      - icon: youtube
        text: Youtube
        href: https://www.youtube.com/@notalnez8088
        

format:
  html:
    theme: darkly 
    css: styles.css
    toc: false

editor: visual

